<Label>
    font_size: 32

<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Label:
            id: name_label
            text: "What's your name?"

        TextInput:
            id: name_input
            multiline: False
            size_hint: (1, 0.5)

        Button:
            size_hint: (1, 0.5)
            text: "Submit"
            on_press: root.press()
